url.start_pages: ['http://joy/notes/Today.html']
url.default_page: 'http://joy/notes/Today.html'
new_instance_open_target: 'window'
content.cookies.accept: no-3rdparty
content.headers.accept_language: fr-FR,fr,de-DE,de,en-GB,en-US,en;q=0.9
content.notifications.enabled: true
content.plugins: true
content.user_stylesheets: ['quaive.css']
completion.cmd_history_max_items: 500
downloads.remove_finished: 5000
#editor.command: ["atom", "-f", "{file}"]
editor.command: ["terminal", "-e", "/run/current-system/sw/bin/nvim -c 'set ft=text|normal {line}G{column0}l' {file}"]
hints:
  mode: 'word'
  dictionary: /home/reinhardt/.local/share/dict/words
  auto_follow_timeout: 500
tabs:
  background: true
  select_on_remove: last-used
  last_close: close
  #XXX Why does this not work? Currently set in config.py
  #padding:
  #  bottom: 3
  #  left: 5
  #  right: 5
  #  top: 2
#colors:
#  statusbar:
#    url:
#      fg: "grey"
#      success.http.fg: "yellow"
#      success.https.fg: "lime"
#    insert:
#      fg: "darkblue"
#      bg: "cyan"
#  tabs:
#    odd:
#      fg: "grey"
#      bg: "#222222"
#    even:
#      fg: "grey"
#      bg: "#222222"
#    selected:
#      odd:
#        fg: "black"
#        bg: "white"
#      even:
#        fg: "black"
#        bg: "white"
#input.insert_mode.auto_load: true
qt.highdpi: true
zoom.default: 100%
fonts:
  web.family.fixed: "Terminus, Monospace, \"DejaVu Sans Mono\", Monaco, \"Bitstream Vera Sans Mono\", \"Andale Mono\", \"Courier New\", Courier, \"Liberation Mono\", monospace, Fixed, Consolas, Terminal"
  prompts: 10pt "Terminus, Monospace, \"DejaVu Sans Mono\", Monaco, \"Bitstream Vera Sans Mono\", \"Andale Mono\", \"Courier New\", Courier, \"Liberation Mono\", monospace, Fixed, Consolas, Terminal"
  statusbar: 10pt "Terminus, Monospace, \"DejaVu Sans Mono\", Monaco, \"Bitstream Vera Sans Mono\", \"Andale Mono\", \"Courier New\", Courier, \"Liberation Mono\", monospace, Fixed, Consolas, Terminal"
  tabs.selected: 10pt "\"Cousine for Powerline\", FreeSans, sans"
  tabs.unselected: 10pt "\"Cousine for Powerline\", FreeSans, sans"
  hints: bold 10pt monospace
  completion.entry: 10pt monospace
  completion.category: bold 10pt monospace
